apiVersion: v1
kind: Service
metadata:
  name: adm-server-1
  namespace: adm
  labels:
    app: adm-server-1
spec:
  type: ClusterIP
  selector:
    app: adm-server-1
  ports:
    - protocol: TCP
      port: 3000 # Puerto del servicio
      targetPort: 3000 # Puerto del contenedor