apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: adm-client-1
  namespace: adm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /adm-1(/|$)(.*)
        backend:
          serviceName: adm-client-1
          servicePort: 8080