name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

jobs:
  client_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: client/etc/Dockerfile
          path: client
          repository: didream/adm-visualizacion-datos-i
          tag_with_ref: true